In [1]:
print("Meet Anshul")
print("Anshul is a software engineer")
print("Anshul is also interested in lots of other things in life")

#Instead of typing Anshul, we can store it in variable 

Meet Anshul
Anshul is a software engineer
Anshul is also interested in lots of other things in life


In [2]:
name = "Anshul"
print("Meet" , name)
print("%s is a software engineer"  %name)
print("%s is also interested in lots of other things in life" %name)

Meet Anshul
Anshul is a software engineer
Anshul is also interested in lots of other things in life


In [3]:
name = "Bhagyashree"
print("Meet" , name)
print("%s is a software engineer"  %name)
print("%s is also interested in lots of other things in life" %name)

Meet Bhagyashree
Bhagyashree is a software engineer
Bhagyashree is also interested in lots of other things in life


In [5]:
#In python variables with the same name holds the same memory space 


name = "Anshul"
name2 = "Bhagyashree"


print(id(name))
print(id(name2))

1761842682320
1761842984944


In [12]:
#int
num = 5
print(num , type(num))
#conversion
print(float(num) , type(float(num)))
print(complex(num) , type(complex(num)))

#float
num = 5.6
print(num ,type(num))
#conversion
print(int(num) , type(int(num)))


#complex
num = 5 + 6j
print(num , type(num))

5 <class 'int'>
5.0 <class 'float'>
(5+0j) <class 'complex'>
5.6 <class 'float'>
5 <class 'int'>
(5+6j) <class 'complex'>


In [5]:
#List , tuples and dictionaries
lst = [1,4,5,2,5,6]
print(lst)
print(lst[0])
print(len(lst))
print(lst[-4:])
print(lst[1::2])

[1, 4, 5, 2, 5, 6]
1
6
[5, 2, 5, 6]
[4, 2, 6]


In [6]:
lst = [1,4,"Python" , 2 , 7.4 , 5]
lst.append("Learning")

In [12]:
nested = [1,2,[2,3,4]]
nested.extend([[5,6,7], [7,8,9]])

In [13]:
nested

[1, 2, [2, 3, 4], [5, 6, 7], [7, 8, 9]]

In [18]:
tpl = (1,2,3)
print(tpl[::-1])

(3, 2, 1)


In [20]:
tpl = 5,6,8
a,b,c = tpl

In [22]:
print(a,b,c)

5 6 8


In [23]:
a , *lst = tpl
print(a , tpl)

In [ ]:
s = {1,2,2,3,3,3,4,5}
print(s)
s[1] = 1 #this won't work as it cannot be assigned 

In [31]:
#arthimetic operators 
a ,b = 10 , 5
print('a + b' , a + b)
print('a - b' , a - b)
print('a * b' , a * b)
print('a / b' , a / b)
print('a // b' , a // b)
print('a % b' , a % b)
print('a ** b' , a ** b)

a + b 15
a - b 5
a * b 50
a / b 2.0
a // b 2
a % b 0
a ** b 100000


In [34]:
count = 0 
count = count + 1
count += 1
print(count)


2


In [36]:
#Relational operators 

a,b = 10 , 5
print(a,b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)

10 5
True
False
True
False
False
True


In [41]:
#Relational operators 


a1, b1, c1 =  10 , 20 , 30 
print(a1,b1,c1)
print(c1>b1 or 1 > b1)
print(not a1 > b1)

10 20 30
True
True


In [48]:
#bitwise operator 


a ,b = 10 , 5 
print((bin(a) , bin(b)))
print(a & b)
print(bin(a|b))
print(bin(a^b))
print(bin(~a))
print(bin(a<<2))

('0b1010', '0b101')
0
0b1111
0b1111
-0b1011
0b101000


In [51]:
#membership operators 

lst = [1,2,3,4,5]
x=2
print(x not in lst)

False


In [54]:
#identity operator 

x = 10 
y = 10
print(x is y)
print(x is not y)

True
False


In [62]:
import math 

x = 9.5
y= 3
print(math.pow(x,y))

x = 9.5
print(math.ceil(x))

print(math.sqrt(x))

print(math.factorial(y))

857.375
10
3.082207001484488
6


In [65]:
#inline input 

name = input("Enter your name \n")
print("Hi" , name)

age = input("Enter your age \n")
print("What's your age" , age ) 

Enter your name 
Anshul
Hi Anshul
Enter your age 
28
What's your age 28


In [3]:
name = input("Enter the word \n")[:4]
print("Hi" , name)

Enter the word 
Anshul 
Hi Ansh


In [6]:
a = int(input("Enter a multiple of 5"))
print(type(a))

Enter a multiple of 510
<class 'int'>


In [2]:
name = input("Enter your name")
print("Hi" , name)


age = input("Enter your age \n")
print("%s is %d years old"%(name , int(age))) 
#everything in input is string , convert the variable first  
#use % sign to name the variables 

Enter your nameAnshul 
Hi Anshul 
Enter your age 
28
Anshul  is 28 years old


In [2]:
#if , while , for , break , continue 

a = int(input("Enter the multiple of 2"))
if a%2 != 0:
    print(a , "This is an odd number")
else:
    print(a , "This is an even number")
    
print("This is what happens next")

Enter the multiple of 22
2 This is an even number
This is what happens next


In [4]:
#if , while , for , break , continue 

a = int(input("Enter the number"))
b = int(input("Enter the number"))
c = int(input("Enter the number"))



if a>b and a>c:
    print(a , "This is the greatest number")
elif b>a and b>c :
    print(b , "This is the greatest number")
else:
    print(c , "This is the greatest number")

Enter the number5
Enter the number9
Enter the number6
9 This is the greatest number


In [7]:
#if , while , for , break , continue 


age = int(input("Enter your age"))
if age >= 60:
    print("You are eligible for the senior citizen discount")
else: #this is the nested script so that i can write multiple scripts
    if age <= 18:
        print("You are eligible for the minor discount")
    else:
        print("You are not eligible for any discount")

Enter your age35
You are not eligible for any discount


In [1]:
#if , while , for , break , continue 

word = "Python"
i = 0
while i <= 5:
    print(i, word)
    i += 1

0 Python
1 Python
2 Python
3 Python
4 Python
5 Python


In [1]:
#if , while , for , break , continue 

lst = []
c = input("Enter 1 to add the list of the element and 0 to exit")
while c != "0":
    lst.append(c)
    c = input("Enter 1 to add the list of the element and 0 to exit")
print(lst)

Enter 1 to add the list of the element and 0 to exitAnshul
Enter 1 to add the list of the element and 0 to exit1
Enter 1 to add the list of the element and 0 to exit90.0
Enter 1 to add the list of the element and 0 to exitMastering Data Science
Enter 1 to add the list of the element and 0 to exit0
['Anshul', '1', '90.0', 'Mastering Data Science']


In [2]:
#if , while , for , break , continue 
word = 'Python'

for w in range(10):
    print(w, word)

0 Python
1 Python
2 Python
3 Python
4 Python
5 Python
6 Python
7 Python
8 Python
9 Python


In [1]:
lst = [1,2,"Hello" , [1,2,3]]
for obj in lst:
    print(obj)

1
2
Hello
[1, 2, 3]


In [2]:
#count the number of vowels in the input

word = input("Enter word ")
count = 0

for i in word:
    if i in ['a' ,'e' ,'i' ,'o' ,'u' ,'A' ,'E' ,'I' ,'O' ,'U']:
        count += 1
print("Number of vowels in %s is %d"%(word , count))


Enter word Anshul Mahajan
Number of vowels in Anshul Mahajan is 5


In [4]:
#Break & Continue

n = 11
for i in range(2, n//2+1):
    if n%i == 0:
        print(n, "is not a prime number")
        break

In [6]:
n = 20 
for i in range(2, n//2+1):
    if n%i != 0:
        continue 
    print("%d is divisible by %d"%(n,i))
        

20 is divisible by 2
20 is divisible by 4
20 is divisible by 5
20 is divisible by 10


In [13]:
#Arrays and Numpy , and Lists and array are not the same thing in python 


from array import *
ar = array('i' , [1,2,3,4,5])
ar.append(-10)
ar.remove(3)
ar = ar*3
print(ar)
print(ar.index(-10))

array('i', [1, 2, 4, 5, -10, 1, 2, 4, 5, -10, 1, 2, 4, 5, -10])
4


In [21]:
import numpy as np 

ar1 = np.array([1,2,3])
print([1,2,3])
print(ar1) # when numpy gets printed it doesn't show comma in the output 

ar2 = np.array([[1,2,3],[4,5,6]])
print(ar2) # when numpy gets printed it doesn't show comma in the output 
print("Dimension : " , ar2.ndim)
print("Size : " , ar2.size)
print("Shape : " , ar2.shape) #shape is extremely important in ML and data fitting and training 
print("Type of elements : " , ar2.dtype)

[1, 2, 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
Dimension :  2
Size :  6
Shape :  (2, 3)
Type of elements :  int32


In [28]:
z = np.zeros((2,2) , dtype = "int")
print(z) #array filled with zeros

z1 = np.full((2,3) , 1)
print(z1)

ar3 = np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])
print(ar3[1,2])

ar3 = np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])
print(ar3[:1,::-1])

[[0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]]
6
[[3 2 1]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [31]:
#numpy functionalities 

print(ar3 + 10)
print(ar3 * 10)
print(ar3.sum())
print(ar3[0].sum())
print(ar3.min())
print(ar3.max())

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
45
6
1
9


In [33]:
#Transpose Numpy 
ar4 = np.array([[1,2,3],[4,5,6]])
ar4.T
print(ar4.T)
print(ar4)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [39]:
#Functions

def fun():
    print("I am going to make it very big ")
fun()

def sum(a ,b):
    print(a +b)
sum(4,5)


def add(a,b):
    s = a + b 
    d = a - b
    return s , d #Here s is tuple 
n = add(971676,6797197)
print(n)

I am going to make it very big 
9
(7768873, -5825521)


In [3]:
#args , kwargs 

def args_kwargs(*myArgs):
    a = myArgs[0] + myArgs[1]
    return a
    print(myArgs[1])
a = args_kwargs(1,2,3,4)
print(a)

3


In [6]:
def args_kwargs(**myKwargs):
    print(myKwargs)
    print(myKwargs['a'] + myKwargs['b'])
args_kwargs(a = 10 , b = 20)
    
#     a = myArgs[0] + myArgs[1]
#     return a
#     print(myArgs[1])
# a = args_kwargs(1,2,3,4)
# print(a)

{'a': 10, 'b': 20}
30


In [8]:
#functions recursive 


def rec(n):
    if n == 1:
        print(n)
        return
    print(n)
    return rec(n-1)
rec(7)

7
6
5
4
3
2
1


In [9]:
#factorial Function 

def fact(n):
    f = 1
    for i in range(1 , n + 1):
        f *=  i
    return f
print(fact(5))

120


In [12]:
#lambda functions 

l = lambda a , b : a +b 
print(l(10,20))

lst = ['a','b','e','o','u','a']
l = list(filter(lambda x : x in ['a' ,'e' ,'i' ,'o' ,'u'] , lst))
print(l)
         

30
['a', 'e', 'o', 'u', 'a']


In [14]:
#lambda functions  , map

lst = ['a','b','e','o','u','a']
result = map(lambda x : chr(ord(x)+1) , lst)
print(list(result))


['b', 'c', 'f', 'p', 'v', 'b']


In [15]:
#lambda functions  , map
#concatenate the lines 

from functools import reduce 
result = reduce(lambda x,y : x + y , lst)
print(result)

abeoua


In [22]:
# from modl import * , this will import all the code from one file to another 

def prime(a):
    for i in range(2,a):
        if a%i == 0:
            print("Number is not prime")
            return 
    print("Number is prime")
    
    
def even(a):
    if a%2 == 0:
        print("Number is even")
    else:
        print("Number is odd")
        
n = int(input("Enter the number : "))
print(prime(n))
print(even(n))

Enter the number : 11
Number is prime
None
Number is odd
None


In [10]:
#OOPS

class Car:
    carType = "Manual" #global variable or feature 
    def __init__(self , year , speed):
        self.year = year #instance feature
        self.speed = speed #instance feature 
    
    @staticmethod
    def welcome():
        print("Welcome to the ar showroom")
    @classmethod
    def type(cls):
        print(print("These classes are " , cls.carType))
    def getSpeed(self):
        print("Maxium Speed is " , self.speed)

BMW = Car(2018 , 155)

Ford = Car(2016 , 140)
AUDI = Car(2017 , 145)

BMW.getSpeed()

class Sedan(Car):  #Inheritance
    def __init__(self , year , speed):
        super().__init__(year, speed)
        print("This is sedan")

class SUV(Car):
    def getSpeed(Self):
        print("Maximum speed is 120 ")

    def openTrunk(self):
        print("Open Trunk")
BMW = Sedan(2018 , 155)
# BMW.openTrunk()

Maxium Speed is  155
This is sedan
